[project]
name = "mvpriskmanagementdashboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.136.1",
    "pandas>=3.0.2",
    "plotly>=6.7.0",
    "pydantic>=2.13.3",
    "streamlit>=1.56.0",
    "uvicorn>=0.46.0",
    "websockets>=16.0",
]
